steps:
  - name: 'ubuntu'
    entrypoint: bash
    args: 
      - '-c'
      - |- 
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        apt-get -y install unzip
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.8/dependency-check-9.0.8-release.zip
        unzip dependency-check-9.0.8-release.zip -y
        current_directory=$(pwd)

        # cd $current_directory
        dependency-check.sh  --project dep-check --scan root/test --output depcheac.html
