# Stage 1: Build stage
FROM python:3.8-slim AS builder

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/

# Stage 2: Production stage
FROM python:3.8-slim AS production

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY --from=builder /app /app

# Install Nginx
RUN apt-get update && apt-get install -y nginx

# Remove the default Nginx configuration
RUN rm /etc/nginx/sites-enabled/default

# Copy the custom Nginx configuration
COPY nginx.conf /etc/nginx/sites-enabled/

# Expose the port Nginx will run on
EXPOSE 80

# Start Nginx and the Django application
CMD ["nginx", "-g", "daemon off;"]
